### ISSUE TITLE
Accelerator support (GPU)

### ISSUE THREAD

**Issue by stefdoerr** [googleapis/python-batch#68]
**Is your feature request related to a problem? Please describe.**
I need to submit GPU jobs to google batch through the python API
 **Describe the solution you'd like**
Make the InstancePolicy.accelerators option work
 **Describe alternatives you've considered**
Not sure, I'd be open to suggestions

Accelerators seem to not be supported yet through the python API https://github.com/googleapis/python-batch/blob/main/google/cloud/batch_v1/types/job.py#L529-L531 even though they seem to be supported through the YAML/JSON config files https://cloud.google.com/batch/docs/create-run-job#gpu-container-job-api

I also looked at the RPC API and  they are also not supported there.

Is there some sort of workaround to get it to work or do I have to give up on using the python API and switch to yaml files and the `gcloud` CLI tool (I'd prefer to avoid that since I'm writing a python library)?

**Comment by parthea** [comment]
Thanks for reporting this @stefdoerr. Googlers see b/258435497 for internal issue

**Comment by parthea** [comment]
The docs are not correct as the feature has been implemented. The issue with the docs will be fixed in #72
